"""initial_schema

Revision ID: e2a22f0b82bb
Revises: 
Create Date: 2026-03-27 12:37:23.058754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a22f0b82bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'ops', 'client', name='role_enum'), nullable=False),
    sa.Column('account_type', sa.Enum('retail', 'institutional', name='account_type_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('metal_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metal', sa.Enum('gold', 'silver', 'platinum', name='metal_enum'), nullable=False),
    sa.Column('price_usd_per_troy_oz', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metal_prices_metal'), 'metal_prices', ['metal'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('token_balances',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('metal', sa.Enum('gold', 'silver', 'platinum', name='metal_enum'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'metal')
    )
    op.create_table('vaults',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deposit_number', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('metal', sa.Enum('gold', 'silver', 'platinum', name='metal_enum'), nullable=False),
    sa.Column('storage_type', sa.Enum('allocated', 'unallocated', name='storage_type_enum'), nullable=False),
    sa.Column('token_amount', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deposit_number')
    )
    op.create_table('unallocated_pools',
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('metal', sa.Enum('gold', 'silver', 'platinum', name='metal_enum'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'metal')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=True),
    sa.Column('metal', sa.Enum('gold', 'silver', 'platinum', name='metal_enum'), nullable=True),
    sa.Column('storage_type', sa.Enum('allocated', 'unallocated', name='storage_type_enum'), nullable=False),
    sa.Column('token_amount', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocated_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('weight_g', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('withdrawal_bars',
    sa.Column('withdrawal_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['allocated_bars.id'], ),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('withdrawal_id', 'bar_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_bars')
    op.drop_table('allocated_bars')
    op.drop_table('withdrawals')
    op.drop_table('unallocated_pools')
    op.drop_table('deposits')
    op.drop_table('vaults')
    op.drop_table('token_balances')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_metal_prices_metal'), table_name='metal_prices')
    op.drop_table('metal_prices')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
